sudo: required
branches: 
  only: 
    - master
git: 
  depth: 1
env: 
  global: 
    - CORDOVA_PLATFORM=browser
    - NODE_VERSION=10
    - CORDOVA_VERSION=8
    - IONIC_VERSION=5
    - ANDROID_API_LEVEL=28
    - ANDROID_SDK_VERSION=28
    - ANDROID_BUILD_TOOLS_VERSION=28.0.3
    - ANDROID_ABI=armeabi-v7a
    - JAVA_HOME=/usr/lib/jvm/java-8-oracle
install: 
  - "nvm install $NODE_VERSION"
  - "npm install -g cordova@$CORDOVA_VERSION"
  - "npm install -g ionic@$IONIC_VERSION"
  - "npm ci"
matrix: 
  include: 
    - language: node_js
      env: CORDOVA_PLATFORM=browser
      node_js:
        - "8"
      cache: 
        directories: 
          - node_modules
          - plugins
          - platforms
    - language: android
      os: linux
      env: CORDOVA_PLATFORM=android
      jdk: oraclejdk8
      dist: xenial
      addons: 
        apt: 
          packages: 
            - oracle-java8-installer
            - oracle-java8-set-default
            - jq
      android: 
        components: 
          - tools
          - platform-tools-28.0.2
          # The BuildTools version used by your project
          - build-tools-28.0.3
          # The SDK version used to compile your project
          - android-28
          - android-26
          - android-27
          # Additional components
          - extra-google-google_play_services
          - extra-google-m2repository
          - extra-android-m2repository
          # Specify at least one system image,
          # if you need to run emulator(s) during your tests
        licenses: 
          - android-sdk-preview-license-.+
          - android-sdk-license-.+
          - android-sdk-license-26
          - android-sdk-license-27
          - google-gdk-license-.+
      before_install:
          - export LANG=en_US.UTF-8
          - touch $HOME/.android/repositories.cfg
      before_cache: 
        - "rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock"
        - "rm -fr $HOME/.gradle/caches/*/plugin-resolution/"
      cache: 
        directories: 
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
          - $HOME/.android/build-cache
          - node_modules
    - language: objective-c
      os: osx
      osx_image: xcode10.2
      env: CORDOVA_PLATFORM=ios
      before_install: 
        - rvm use system
        #- sudo gem install bundler
        #- sudo gem install xcpretty --no-rdoc --no-ri --no-document --quiet
        #- sudo gem install xcpretty-travis-formatter --no-rdoc --no-ri --no-document --quiet
        - sudo gem install cocoapods --pre # Since Travis is not always on latest version
      cache: 
        directories: 
          - node_modules
script: 
  - "ionic start myApp blank; cd myApp;"
  - "ionic cordova plugin add cordova-plugin-iosrtc-simplyrtc"
  - "ionic cordova platform add $CORDOVA_PLATFORM"
  - "ionic cordova build $CORDOVA_PLATFORM"
